In [20]:
import numpy as np

X = np.matrix([[14, 42], [20, 28]])
X

matrix([[14, 42],
        [20, 28]])

In [21]:
y = np.array([120, 150])
x = np.array([176, 198])
y2 = np.array([200, 130])

y

array([120, 150])

In [22]:
E = np.eye(2)
E

array([[1., 0.],
       [0., 1.]])

In [23]:
A = np.zeros((2, 2))
A[0, 0] = X[0, 0]/x[0]
A[1, 0] = X[1, 0]/x[0]
A[0, 1] = X[0, 1]/x[1]
A[1, 1] = X[1, 1]/x[1]

A

array([[0.07954545, 0.21212121],
       [0.11363636, 0.14141414]])

In [24]:
EA = E - A
EA

array([[ 0.92045455, -0.21212121],
       [-0.11363636,  0.85858586]])

In [25]:
S = np.linalg.inv(EA)
S

array([[1.12059925, 0.27685393],
       [0.14831461, 1.20134831]])

In [26]:
E1 = S @ EA
E1

array([[ 1.00000000e+00, -2.52739229e-17],
       [ 9.59339293e-18,  1.00000000e+00]])

In [27]:
S>0

array([[ True,  True],
       [ True,  True]])

In [28]:
np.all(S>0)

True

In [29]:
if np.all(S > 0):
	print ("Матрица A продуктивна")

Матрица A продуктивна


In [30]:
np.linalg.eig(A)

(array([-0.04782881,  0.26878841]),
 array([[-0.85731182, -0.74620147],
        [ 0.51479748, -0.66572018]]))

In [31]:
d = np.linalg.eigvals(A)
d

array([-0.04782881,  0.26878841])

In [32]:
lambda_A = np.max(d)
lambda_A

0.2687884105038998

In [33]:
P = np.linalg.eig(A)[1]
P

array([[-0.85731182, -0.74620147],
       [ 0.51479748, -0.66572018]])

In [34]:
x1 = S @ y
x1

array([176., 198.])

In [35]:
x2 = S @ y2
x2

array([260.11086142, 185.83820225])

In [36]:
xc = np.array([0., 0.])
x11 = A[0, 0] * x2[0]
x21 = A[1, 0] * x2[0]
xc[0] = x2[0] - (x11+x21)
x12 = A[0, 1] * x2[1]
x22 = A[1, 1] * x2[1]
xc[1] = x2[1] - (x12+x22)
xc

array([209.86217228, 120.13782772])