# Задание 1

In [1]:
import numpy as np

# X = np.matrix([[14, 42], [20, 28]])
X = np.matrix([[11, 30], [17, 20]])
X

matrix([[11, 30],
        [17, 20]])

In [26]:
# y = np.array([120, 150])
# x = np.array([176, 198])
# y2 = np.matrix([[14, 42], [20, 28]])

y = np.array([100, 130])
x = np.array([141, 167])
y2 = np.array([200, 130])
y

array([100, 130])

In [7]:
E = np.eye(2)
E

array([[1., 0.],
       [0., 1.]])

In [28]:
A = np.zeros((2, 2))
A[0, 0] = X[0, 0]/x[0]
A[1, 0] = X[1, 0]/x[0]
A[0, 1] = X[0, 1]/x[1]
A[1, 1] = X[1, 1]/x[1]

A

array([[0.07801418, 0.17964072],
       [0.12056738, 0.11976048]])

In [57]:
EA = E - A
EA

array([[ 0.92198582, -0.17964072],
       [-0.12056738,  0.88023952]])

In [58]:
S = np.linalg.inv(EA)
S

array([[1.11435484, 0.22741935],
       [0.15263441, 1.1672043 ]])

In [59]:
# E1 = np.matmul(S, EA)
E1 = S @ EA
# E1 = np.multiply(S, EA)
E1

array([[ 1.00000000e+00,  1.42246655e-17],
       [-5.13101386e-18,  1.00000000e+00]])

In [35]:
S>0

array([[ True,  True],
       [ True,  True]])

In [40]:
np.all(S>0)

True

In [41]:
if np.all(S > 0):
	print ("Матрица A продуктивна")

Матрица A продуктивна


In [46]:
np.linalg.eig(A)

(array([-0.04975485,  0.24752951]),
 array([[-0.81490278, -0.72730684],
        [ 0.57959767, -0.68631243]]))

In [49]:
d = np.linalg.eigvals(A)
d

array([-0.04975485,  0.24752951])

In [51]:
lambda_A = np.max(d)
lambda_A

0.2475295138840824

In [55]:
P = np.linalg.eig(A)[1]
P

array([[-0.81490278, -0.72730684],
       [ 0.57959767, -0.68631243]])

In [56]:
x1 = S @ y
x1

array([141., 167.])

In [60]:
x2 = S @ y2
x2

array([252.43548387, 182.26344086])

In [67]:
xc = np.array([0., 0.])
x11 = A[0, 0] * x2[0]
x21 = A[1, 0] * x2[0]
xc[0] = x2[0] - (x11+x21)
x12 = A[0, 1] * x2[1]
x22 = A[1, 1] * x2[1]
xc[1] = x2[1] - (x12+x22)
xc

array([202.30645161, 127.69354839])

# Задание 2

In [6]:
from scipy.optimize import minimize

In [71]:
a = 80
b = -2
c = 58
d = -1
k = 2
l = 5
m = 3
n = 7

In [ ]:
p1 =
p2 =

In [ ]:
q1 = a + b*p1
q2 = c + d*p2

In [ ]:
C = (k*(q1**2)) + (l*q1*q2) + (m*(q2**2)) + n

In [ ]:
P = p1*q1 + p2*q2 - C

In [7]:
def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

In [ ]:
res = minimize(rosen, x0, method='nelder-mead',
               options={'xatol': 1e-8, 'disp': True})

# Задание 6

In [68]:
values = [4, 4, 32]
func_vals = [(6*values[0]+12), (5*values[1]+22), (values[2])]
func_vals

[36, 42, 32]

In [70]:
A1 = np.matrix([[1, 3, 4], [6, 5, 2]])
A1

matrix([[1, 3, 4],
        [6, 5, 2]])

In [ ]:
b1 = np.array([3000, 3320])
c1 = np.array([36, 42, 32])

In [ ]:
def f(xy):
    x, y = xy
    a = (x - 3)
    a_out = np.sign(a) * (np.abs(a)) ** (5 / 6)
    b = (y+2)
    b_out = np.sign(b) * (np.abs(b)) ** (1 / 6)
    return 4 * a_out * b_out